@startuml
title 刪除帳號
|使用者|
start
:進入帳號安全介面;
:選擇刪除帳號;
:確認危險操作;
if (是否確認刪除？) then (取消)
stop
else (確認)
  :輸入密碼;
  |系統|
  if (密碼正確？) then (是)
    :刪除帳號資料;
    :返回成功回應;
  else (否)
    :返回密碼錯誤訊息;
endif
|使用者|
:顯示回應;
stop
@enduml