@startuml
title 互評
|活動參與者|
start
:進入互評頁面;

|系統|
if (活動時間結束&活動狀態已完成) then (是)
  |系統|
  :開放互評功能;
  :更新頁面;
  |活動參與者|
  :選擇活動參與者;
  :填寫內容;
  :提交評價;
  |系統|
  :儲存資料;
  :更新頁面;
  :返回成功互評;
else (否)
  :回傳未開放互評;
  |活動參與者|
endif
|活動參與者|
:顯示內容;
stop
@enduml