@startuml
title 審核活動申請
|活動創建者|
start
:查看待審核名單;
:選擇用戶;
:選擇操作;

|系統|
if (是否接受?) then (拒絕)
  |活動創建者|
  :輸入拒絕原因;
  :送出;
else (接受)
  |系統|
  :更新參與者名單;
  :使用者狀態新增為活動參與者;
  |活動創建者|
endif
|系統|
:更新審核名單;
:返回審核;
|活動創建者|
:顯示結果;
stop
@enduml