@startuml
title 審核好友申請
|使用者|
start
:進入好友待回應介面;
:查看申請;
if (有申請？) then (沒有)
  stop
else (有)
  :選擇用戶;
  :選擇操作;
  |系統|
  if (是否接受？) then (接受)
    :更新好友關係;
    :返回接受回應;
  else (拒絕)
    :取消申請;
    :返回拒絕回應;
  endif
endif
|使用者|
:顯示回應;
stop
@enduml