@startuml
title 忘記密碼
|使用者|
start
:選擇忘記密碼;
:輸入電子郵件;
|系統|
if (電子郵件存在？) then (是)
  :發送重置密碼連結;
  :Gmail SMTP 發送驗證碼;
else (否)
  :返回錯誤訊息;
  stop
endif
|使用者|
:輸入驗證碼;
:輸入新密碼;
:確認新密碼;
|系統|
if (驗證成功？) then (是)
  :返回成功回應;
else (否)
  :返回失敗回應;
endif
|使用者|
:顯示回應;
:返回登入頁面;
stop
@enduml